// ============================================
// AUTOMATED FEEDBACK REQUEST CRON (Issues #77, #60)
// Daily job: Day 1 after checkout - send feedback link
// ============================================

import { NextRequest, NextResponse } from "next/server";
import { createServerClient } from "@/lib/supabase/client";
import { sendWhatsAppMessage, isTwilioAvailable } from "@/lib/twilio/client";

// This endpoint is called by Vercel Cron
// Schedule: Daily at 10:00 AM Cartagena time (15:00 UTC)

const APP_URL =
  process.env.NEXT_PUBLIC_APP_URL || "https://ops.tinyvillagecartagena.com";

const FEEDBACK_MESSAGE_ES = `Hola {guest_name}!

Gracias por hospedarse en Tiny Village Cartagena! 🏝️

Queremos saber como fue su experiencia. Su opinion es muy importante para nosotros y nos ayuda a mejorar.

Por favor tome 30 segundos para calificar su estancia:
{feedback_link}

Gracias por elegirnos!
El equipo de TVC`;

const FEEDBACK_MESSAGE_EN = `Hi {guest_name}!

Thank you for staying at Tiny Village Cartagena! 🏝️

We'd love to know about your experience. Your feedback is very important to us and helps us improve.

Please take 30 seconds to rate your stay:
{feedback_link}

Thank you for choosing us!
The TVC Team`;

export async function POST(request: NextRequest) {
  try {
    // Verify cron secret
    const authHeader = request.headers.get("authorization");
    const cronSecret = process.env.CRON_SECRET;

    if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    if (!isTwilioAvailable()) {
      return NextResponse.json({
        success: false,
        error: "Twilio not configured",
        message:
          "Set TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, and TWILIO_WHATSAPP_FROM",
      });
    }

    const supabase = createServerClient();

    // Get yesterday's date (guests who checked out yesterday)
    const yesterday = new Date();
    yesterday.setDate(yesterday.getDate() - 1);
    const checkOutDate = yesterday.toISOString().split("T")[0];

    // Find guests who checked out yesterday and haven't received feedback request
    const { data: checkouts, error: checkoutsError } = await supabase
      .from("villa_bookings")
      .select("*")
      .eq("check_out", checkOutDate)
      .eq("status", "checked_out")
      .not("guest_phone", "is", null);

    if (checkoutsError) {
      console.error("[Feedback Cron] Checkouts fetch error:", checkoutsError);
      return NextResponse.json(
        { success: false, error: "Failed to fetch checkouts" },
        { status: 500 },
      );
    }

    if (!checkouts || checkouts.length === 0) {
      return NextResponse.json({
        success: true,
        message: "No checkouts to process",
        processed: 0,
      });
    }

    const results = {
      processed: 0,
      sent: 0,
      skipped: 0,
      failed: 0,
      details: [] as { guest: string; status: string; error?: string }[],
    };

    for (const booking of checkouts) {
      results.processed++;

      // Check if we already have a pending feedback for this booking
      const { data: existing } = await supabase
        .from("guest_feedback")
        .select("id")
        .eq("booking_id", booking.id)
        .single();

      if (existing) {
        results.skipped++;
        results.details.push({
          guest: booking.guest_name,
          status: "skipped",
          error: "Feedback already exists for this booking",
        });
        continue;
      }

      // Check if we sent feedback request to this phone recently
      const { data: recentFeedback } = await supabase
        .from("guest_feedback")
        .select("id")
        .eq("guest_phone", booking.guest_phone)
        .gte(
          "created_at",
          new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        )
        .single();

      if (recentFeedback) {
        results.skipped++;
        results.details.push({
          guest: booking.guest_name,
          status: "skipped",
          error: "Feedback request sent to this phone within 7 days",
        });
        continue;
      }

      // Create feedback record (token will be auto-generated by trigger)
      const { data: feedbackRecord, error: createError } = await supabase
        .from("guest_feedback")
        .insert({
          booking_id: booking.id,
          reservation_id: booking.reservation_id || null,
          villa_id: booking.villa_id,
          guest_name: booking.guest_name,
          guest_phone: booking.guest_phone,
          guest_email: booking.guest_email || null,
          check_in_date: booking.check_in,
          check_out_date: booking.check_out,
          language: booking.language || "es",
          source: "survey",
        })
        .select("id, review_link_token")
        .single();

      if (createError || !feedbackRecord) {
        results.failed++;
        results.details.push({
          guest: booking.guest_name,
          status: "failed",
          error: "Failed to create feedback record",
        });
        continue;
      }

      // Build feedback link
      const feedbackLink = `${APP_URL}/feedback/${feedbackRecord.review_link_token}`;

      // Prepare message
      const language = booking.language || "es";
      const messageTemplate =
        language === "en" ? FEEDBACK_MESSAGE_EN : FEEDBACK_MESSAGE_ES;
      const message = messageTemplate
        .replace("{guest_name}", booking.guest_name || "estimado huesped")
        .replace("{feedback_link}", feedbackLink);

      // Send WhatsApp message
      const sendResult = await sendWhatsAppMessage(
        booking.guest_phone!,
        message,
      );

      if (sendResult.success) {
        // Log successful send
        await supabase.from("feedback_automation_log").insert({
          feedback_id: feedbackRecord.id,
          booking_id: booking.id,
          guest_name: booking.guest_name,
          guest_phone: booking.guest_phone,
          action_type: "feedback_requested",
          action_details: {
            message_sid: sendResult.sid,
            feedback_link: feedbackLink,
            language,
          },
          status: "success",
        });

        results.sent++;
        results.details.push({
          guest: booking.guest_name,
          status: "sent",
        });
      } else {
        // Log failed send
        await supabase.from("feedback_automation_log").insert({
          feedback_id: feedbackRecord.id,
          booking_id: booking.id,
          guest_name: booking.guest_name,
          guest_phone: booking.guest_phone,
          action_type: "feedback_requested",
          action_details: {
            error: sendResult.error,
            language,
          },
          status: "failed",
          error_message: sendResult.error,
        });

        results.failed++;
        results.details.push({
          guest: booking.guest_name,
          status: "failed",
          error: sendResult.error || "Twilio error",
        });
      }
    }

    console.log(
      `[Feedback Cron] Completed: ${results.sent} sent, ${results.skipped} skipped, ${results.failed} failed`,
    );

    return NextResponse.json({
      success: true,
      message: `Processed ${results.processed} checkouts`,
      results,
    });
  } catch (error) {
    console.error("[Feedback Cron] Error:", error);
    return NextResponse.json(
      { success: false, error: "Cron job failed" },
      { status: 500 },
    );
  }
}

// GET for health check
export async function GET() {
  return NextResponse.json({
    status: "ok",
    job: "feedback-requests",
    schedule: "Daily at 10:00 AM Cartagena time",
    description: "Sends feedback request to guests who checked out yesterday",
  });
}
